### PR TITLE
Exclude HIDAPI support on iOS to avoid `CoreBluetooth` references

### PR DESCRIPTION
**Pull request by frenzibyte**
Intended to (fix) https://github.com/ppy/osu/pull/31162#issuecomment-2550452912. The constant is documented in https://wiki.libsdl.org/SDL3/CategoryHIDAPI, read last paragraph.

This can be confirmed to work by checking the SDL3 binary against `otool`. Here's a diff between last package and this PR:
```diff
diff --git a/./a b/./b
index 93cbf28..93c2131 100644
--- a/./a
+++ b/./b
@@ -1,4 +1,4 @@
-/Users/salman/.nuget/packages/ppy.sdl3-cs/2024.1128.0/runtimes/ios/native/SDL3.xcframework/ios-arm64/SDL3.framework/SDL3:
+SDL3:
        @rpath/SDL3.framework/SDL3 (compatibility version 108.0.0, current version 108.0.0)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox (compatibility version 1.0.0, current version 1000.0.0)
@@ -14,7 +14,6 @@
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.120.2)
        /System/Library/Frameworks/AVFoundation.framework/AVFoundation (compatibility version 1.0.0, current version 2.0.0)
-       /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics (compatibility version 64.0.0, current version 1774.5.3)
        /System/Library/Frameworks/CoreMedia.framework/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/CoreMotion.framework/CoreMotion (compatibility version 1.0.0, current version 2890.16.16)
```

### CODE REVIEW

**Review by Susko3 — COMMENTED** [review]
Every function in `SDL_hidapi.g.cs` should be marked with `[UnsupportedOSPlatform("iOS")]`.

**Comment by frenzibyte** [comment]
The attribute has been added manually to all members of the `SDL_hidapi.g.cs` file. Ideally this should've been done by ClangSharp but wildcard support was broken and not resolved until https://github.com/dotnet/ClangSharp/pull/567 which is seemingly not included in the latest release of the tool.

**Comment by smoogipoo** [comment]
Instead of manually adding to the `.g.cs` files, can you add the non-wildcard mappings in the `.rsp` instead?

**Comment by frenzibyte** [comment]
Ah, better idea for now.

**Comment by frenzibyte** [comment]
Closing as we've agreed in https://github.com/ppy/osu/pull/31162 to just state that we don't use CoreBluetooth's API.

**Pull request closed without merging**
